### ISSUE TITLE
Wrong smear placement when used with LspSaga plugin

### ISSUE THREAD

**Issue by jayadamsmorgan** [sphamba/smear-cursor.nvim#17]
LspSaga plugin adds LSP symbols on top of the buffer and because of that the smearing effect is 1 line above. Is there any workaround that could be done?

**Comment by L-BloodStone** [comment]
I'm having the same problem. It breaks after commit `2787915`. Before that It was fine.

**Comment by jayadamsmorgan** [comment]
Awesome, thank you!
