### ISSUE TITLE
animation rendered on the wrong line

### ISSUE THREAD

**Issue by atinylittleshell** [sphamba/smear-cursor.nvim#18]
Awesome plugin first of all! 

See video below - animation is somehow showing one line above where my cursor is. Also, I use transparent background - how to make smear work well with that? 

https://github.com/user-attachments/assets/d5e4feaa-d057-48cc-8f0b-f476f882631a

**Comment by leokang94** [comment]
I'm having the same problem.

**Comment by sphamba** [comment]
Do you have annotations above the buffer or above lines in your file? In that case, #16 (branch [`fix-concealed`](https://github.com/sphamba/smear-cursor.nvim/tree/fix-concealed)) might fix your issue.

For transparency, I opened a feature issue #19

**Comment by atinylittleshell** [comment]
possibly! happy to try the concealed fix once that's merged!

**Comment by leokang94** [comment]
@sphamba In my case, `bracnh fix-concealed` seems to have solved this issue nicely! Thanks for the quick check, I appreciate it.
