### ISSUE TITLE
Is vertical bar supported or only block shape?

### ISSUE THREAD

**Issue by rodhash** [sphamba/smear-cursor.nvim#33]
Ask your question about configuring or using smear-cursor here.

When cursor shape is set to vertical bar, would be nice to keep the cursor as is but today cursor is changed to block.

Is this supported?

This is neovide behavior (without changing cursor shape):
<img src="https://github.com/user-attachments/assets/2fce556b-63af-431e-98dc-646403ceda4b" width="158">

This is what I have with smear-cursor:
<img src="https://github.com/user-attachments/assets/3c286884-e201-429a-943c-b9cfe1f913d2" width="158">

I tried playing with these [settings](https://github.com/sphamba/smear-cursor.nvim/blob/5babdd4017658bfd2b52ebf916c513ff914d1dc5/lua/smear_cursor/draw.lua#L6-L11) but no luck so far. It always change to block in my tests.

When moving to the side I guess it's expected to see a block char, neovide does that too but when moving up / down it looks nicer to keep the cursor as a vertical bar (like neovide).

Would this be supported?

I actually tried doing that in the settings above but didn't quite work for me.

One more example to better illustrate this. When doing small moves, it feels a bit weird to see cursor changing to block:
<img src="https://github.com/user-attachments/assets/fd8022c2-60b7-4d35-b746-079f73a17bc9" width="258">

## Environment (optional)

- OS: mac sequoia 15.1.1
- Terminal: iTerm2
- Neovim version: NVIM v0.11.0-dev-1028+g6dad1f9f1
- Smear-cursor version/commit: 5babdd4

**Comment by sphamba** [comment]
I believe we are talking about normal mode (the plugin should not smear in insert mode). Unfortunately, the vertical bar cursor is currently unsupported. I opened a new issue (#34) that would cover this one and #7.

In the meantime, you could try switching to the block cursor in normal mode. I think it makes more sense, for example when moving with `e` or `ge`, inserting with `a`, replacing with `r`... 😉

**Comment by rodhash** [comment]
ok, thanks.

**Comment by sphamba** [comment]
Added an option. You can try the following options:
```lua
opts = {
  vertical_bar_cursor = true,
  matrix_pixel_threshold = 0.3,
}
```
It doesn't really look good though.
