### ISSUE TITLE
Ctrl D half scroll has no effect

### ISSUE THREAD

**Issue by ckangnz** [sphamba/smear-cursor.nvim#40]
When you use ctrl u, it has smear cursor effect but ctrl d doesn't. 

## Environment

- OS: macos
- Terminal: iterm2
- Neovim version: latest
- Smear-cursor version/commit: latest

**Comment by sphamba** [comment]
Could you share a screen cap of the behavior you observe? Do you mean your cursor is moving but without the smear appearing?
Both <C-u> and <C-d> should keep the cursor on the same screen line, until the end of the buffer (top or bottom) is reached.

**Comment by NStefan002** [comment]
I'm experiencing the same issue, here is a screen recording.


https://github.com/user-attachments/assets/8378cb45-364e-4591-8f4d-183c3cedee59


If the cursor jumps within the same column, the trail does not appear.

My config, if it matters:
```lua
{
    "sphamba/smear-cursor.nvim",
    event = "VimEnter",
    opts = {
        cursor_color = "#ff8800",
        stiffness = 0.6,
        trailing_stiffness = 0.1,
        trailing_exponent = 5,
        gamma = 1,
    },
},
```

**Comment by bew** [comment]
I'm pretty sure the plugin needs to subscribe to `WinScrolled` event, and process buffer position changes accordingly.

I think it's related to #51 for the logic around buffer-space position vs screen-space position.

**Comment by sphamba** [comment]
As @bew suggested, this is indeed due to the cursor currently moving in screen space rather than buffer space. So what's shown in a [comment above](https://github.com/sphamba/smear-cursor.nvim/issues/40#issuecomment-2525238627) is the current intended behavior. See #51 for further info
