### ISSUE TITLE
Invalid window id

### ISSUE THREAD

**Issue by ColinKennedy** [sphamba/smear-cursor.nvim#42]
When using https://github.com/troydm/zoomwintab.vim or https://github.com/fasterius/simple-zoom.nvim, I've found that sometimes smear-cursor loses track of the window ID and creates this error

```
Error executing vim.schedule lua callback: .../nvim/bundle/smear-cursor.nvim/lua/smear_cursor/draw.lua:44: Invalid window id: 1002
stack traceback:
        [C]: in function 'nvim_win_get_buf'
        .../nvim/bundle/smear-cursor.nvim/lua/smear_cursor/draw.lua:44: in function 'draw_character_floating_window'
        .../nvim/bundle/smear-cursor.nvim/lua/smear_cursor/draw.lua:115: in function 'draw_character'
        .../nvim/bundle/smear-cursor.nvim/lua/smear_cursor/draw.lua:154: in function 'draw_partial_block'
        .../nvim/bundle/smear-cursor.nvim/lua/smear_cursor/draw.lua:273: in function 'draw_horizontally_shifted_sub_block'
        .../nvim/bundle/smear-cursor.nvim/lua/smear_cursor/draw.lua:283: in function 'draw_block_function'
        .../nvim/bundle/smear-cursor.nvim/lua/smear_cursor/draw.lua:415: in function 'draw_vertical_ish_line'
        .../nvim/bundle/smear-cursor.nvim/lua/smear_cursor/draw.lua:481: in function 'draw_line'
        .../bundle/smear-cursor.nvim/lua/smear_cursor/animation.lua:39: in function 'animate'
        .../bundle/smear-cursor.nvim/lua/smear_cursor/animation.lua:77: in function 'change_target_position'
        ...vim/bundle/smear-cursor.nvim/lua/smear_cursor/events.lua:15: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

When this issue occurs, the error shows at every any cursor movement, making Neovim effectively unusable. I have to restart Neovim and try again.

## Environment

- OS: Ubuntu 22.04
- Terminal: bash
- Neovim version: NVIM v0.11.0-dev-1157+g434d5936b6
- Smear-cursor version/commit: f77177a

**Comment by sphamba** [comment]
I added a way to filter out the floating windows created by smear-cursor. You can add this to the window-picker config:
```lua
require("window-picker").setup({
  filter_rules = {
    bo = {
      filetype = { "smear-cursor" }
    }
  }
})
```

**Comment by sphamba** [comment]
I didn't encouter any issues when testing troydm/zoomwintab.vim, but I see where things could go wrong. I will work on the way smear-cursor keeps track of its windows

**Comment by sphamba** [comment]
I pushed an attempt of fix. Please tell me if you still encounter issues. I'll close the issue later if I do not hear back from you :)

**Comment by ColinKennedy** [comment]
So far so good. I will let you know if it comes up again. Thank you for your fix!
