### ISSUE TITLE
Porting to Rio terminal

### ISSUE THREAD

**Issue by raphamorim** [sphamba/smear-cursor.nvim#48]
Hey there, super awesome project!!!

I am actually considering to add this on Rio terminal natively so would work besides nvim. Is ok if follow your implementation and port to Rio https://github.com/raphamorim/rio ?? (or even if you would have interest on contribute)

Again thx for the project!

**Comment by raphamorim** [comment]
> However, due to the license I put on my code, I'll have to give you a formal written approval, since Rio is not under a GPL license.

Sounds good, I will give a thought about proceed with your implementation or write a custom one to learn. In any case I will ping here either way <3

> How are legacy computing symbols supported?

With cascadia code it should have support on Rio.

> There are currently two different implementations of how the smear is rendered. The one on v0.2.0 (shown in the demo vid), that renders two connected cursors on a line, and the one on master (wip, see https://github.com/sphamba/smear-cursor.nvim/issues/47), that renders a quad and is currently messier. Let me know which one you would choose. The code you are interested in would be in animate.lua and draw.lua.

Sounds good!! btw do you have discord? In case want to contact you :D

> Sadly, I don't think I'll have the time to contribute on Rio, but I'll be happy to keep an eye on the code and pull requests!

No worries and I appreciate any input you have on it!!

**Comment by raphamorim** [comment]
Thank you for your reply! I appreciate 🙏

**Comment by sphamba** [comment]
@raphamorim fyi, I finished implementing rendering the smear as a quad. You can compare the look and capabilities of v0.3.0 vs v0.2.0 and see which one you prefer!
