### ISSUE TITLE
Cursor height grow when animating

### ISSUE THREAD

**Issue by gjf7** [sphamba/smear-cursor.nvim#49]
Thanks for this awesome plugin!

https://github.com/user-attachments/assets/49330127-97d9-4adb-bd18-1dfcd8862539

Probably related to my terminal font setting, like line hight are different with font size ?
<img width="578" alt="image" src="https://github.com/user-attachments/assets/4811c454-2c39-4aaf-a1c0-d97b48dc4b98">

## Environment

- OS: MacOS 15.1
- Terminal: iTerm 2
- Neovim version: NVIM v0.11.0-dev-1267+gc1378413c1
- Smear-cursor version/commit: 0.2.0

**Comment by sphamba** [comment]
Smear-cursor uses block symbols to render the smear. You can try pasting `{ "█", "▇", "▆", "▅", "▄", "▃", "▂", "▁", " " }` in your terminal to see what they look like. I think that the blocks are indeed taking the same height as your line height. It seems that the indicators of matching parenthesis have the same problem on your screen cap. Sadly, there is no way of rendering blocks smaller than those symbols (they can only have the top cropped or the bottom cropped, but not both at the same time)

Perhaps what you would need to do is to match the line height to the font size, and put a vertical spacing between the lines instead?
