### ISSUE TITLE
Buffers & Windows keep increasing

### ISSUE THREAD

**Issue by folke** [sphamba/smear-cursor.nvim#5]
The total number of open buffers/windows keeps increasing.
Neovim became really slow at some point, and it seemed there were over a 1000 buffers and windows open,
created by smear.

Apart from that, I really like how it looks :)

My options:

```lua
{
    legacy_computing_symbols_support = true,
    hide_target_hack = false,
  }
```

**Comment by sphamba** [comment]
Thank you for raising this issue!

Indeed, I made the choice to keep floating windows open, because creating them the first time can be slow due to interaction with syntax highlighting plugins (namely vim-airline, with `BufWinEnter` and `BufUnload` events). That said, I'll work on a garbage collection mechanism that get rids of inactive floating windows :)

**Comment by folke** [comment]
You should probably also set the `noautocmd` option when creating a window, so that other plugins won't trigger autocmds.

**Comment by folke** [comment]
Maybe just create a fixed number of windows and then re-use those? (as long as they're valid)

**Comment by sphamba** [comment]
Windows are already reused (that's why I don't close them). And there must be enough of them to draw every cell that cannot be an extmark, because I naively use one window per cell 🥴. Also, there is one set of window per tab, which could explain how you have so many. Deleting the unused windows (eg those on invisible tabs) would be my way to go

**Comment by sphamba** [comment]
> My options:
> 
> ```lua
> {
>     legacy_computing_symbols_support = true,
>     hide_target_hack = false,
>   }
> ```

I am curious about which font you use that supports legacy computing symbols. 😃

**Comment by folke** [comment]
ok, that explains it. In my case that would eventually get to 15104 windows. (lines * columns)
I don't use tabs, so that's fine.
In terms of re-use I was thinking of just keeping enough windows needed to render a trail. Like 20 or so?
And then just reposition them.
So keep track if a window is used right now and if not re-use it to render a cell and re-position it?

**Comment by folke** [comment]
Something else that could work, is to have just one transparent window covering the whole screen on a buf with empty lines equal to `vim.o.lines`. You could then use nvim_set_extmark with fixed win_col offsets.

but you may have already tried that :)

**Comment by folke** [comment]
To trigger the issue, just open a split with two buffers and then keep switching between both buffers.
Not need to move inside the buffer. Just keep switching to and back.
`#vim.api.nvim_list_wins()` keeps increasing in my case.

**Comment by folke** [comment]
idle CPU also keeps increasing and gets close to 100% after a while

**Comment by sphamba** [comment]
> To trigger the issue, just open a split with two buffers and then keep switching between both buffers. Not need to move inside the buffer. Just keep switching to and back. `#vim.api.nvim_list_wins()` keeps increasing in my case.

I cannot reproduce with my current config on commit `8505320`. My window count stagnates below 40.

**Comment by sphamba** [comment]
Could it be that the smear-cursor plugin gets periodically silently reloaded, resulting in reinitializing the variables that contains the list of references to opened windows (thus forgetting that windows already exist)?
The (local) variables in question are in `lua/smear_cursor/draw.lua`, `window_ids` and `n_active_windows`

**Comment by sphamba** [comment]
Well, I made the lists of windows global, just in case. You can try commit `9b10c94`

**Comment by folke** [comment]
> Could it be that the smear-cursor plugin gets periodically silently reloaded?

Nope, nothing in my config does that.

I think I can no longer trigger the issue right now. Might've been on an older commit.

I'm still on the commit before 9b10c94.

Will close this issue for now and see if it happens again.

Thanks!
