### ISSUE TITLE
Support for non-RGB terminal color

### ISSUE THREAD

**Issue by bew** [sphamba/smear-cursor.nvim#50]
When `termguicolors` is not set in neovim, there is no way to configure the cursor color.

I'm aware you have code to manipulate RGB to apply gamma / transparency / color blending.
But I really only need (I think?) a ramp of colors, which I could give with multiple groups using the 256-colors palette 🤔

**Comment by sphamba** [comment]
Since highlight groups are created on the fly, it is indeed not currently possible to simply define them yourself. 
With the current implementation, one hacky way to go would be to manually trigger the creation of the highlight groups to then override them yourself:
```lua
-- In a .lua script

local config = require("smear_cursor.config")
local color = require("smear_cursor.color")

for i = 1, config.color_levels do
  color.get_hl_group({ level = i })
  color.get_hl_group({ level = i, inverted = true })
end

-- Then define your highlight groups
```

The name of the highlight groups are `SmearCursorNormalX` and `SmearCursorNormaInvertedX`, with `X` going from `1` to  `config.color_levels`.

We'll have to make it easier somehow. Good luck

**Comment by bew** [comment]
Hmm thx for the scaffold.
What are the inverted color groups for?
Can they be the exact same groups as the normal ones, with `reverse = true` ? Or do I have to choose colors for them?

**Comment by sphamba** [comment]
If you don't use a font that has legacy computing symbols, some block symbols will be missing their symmetric counterpart. Still, they can be rendered using inverted foreground and background colors on available symbols for a similar effect. You can use the same colors with `reverse = true`

**Comment by bew** [comment]
For the record, this is what I use now:
```lua
    -- @2024-12 the plugin doesn't expose a way to customize hl groups as they are created
    -- on-the-fly based on various RGB colors (not terminal colors).
    -- So we need to get creative, and manually trigger group creation and override them.
    -- REF: https://github.com/sphamba/smear-cursor.nvim/issues/50#issuecomment-2525347852
    local config = require("smear_cursor.config")
    local color = require("smear_cursor.color")
    for i = 1, config.color_levels do
      color.get_hl_group({ level = i })
      -- note: my config doesn't seem to ever use the inverted color groups
      -- color.get_hl_group({ level = i, inverted = true })
    end
    -- NOTE: assert(#palette == config.color_levels) !
    local smear_palette_fire = {
      { ctermfg = 137 },
      { ctermfg = 136 },
      { ctermfg = 130 },
      { ctermfg = 166 },
    }
    local smear_palette_darkwhite = {
      { ctermfg = 235 },
      { ctermfg = 240 },
      { ctermfg = 245 },
      { ctermfg = 255 },
    }
    local smear_palette = smear_palette_fire
    for i, hl_spec in ipairs(smear_palette) do
      vim.api.nvim_set_hl(0, "SmearCursorNormal"..i, hl_spec)
    end
```
<details>
<summary>Palettes</summary>

![image](https://github.com/user-attachments/assets/a4602d3c-a86a-4e22-8a98-e668856a9d86)

</details>


https://github.com/user-attachments/assets/3810a50b-c60f-43d0-b674-763952b27616

:heart: :sparkles:

**Comment by bew** [comment]
Hmm it's not working perfectly well though, when I re-apply my colorscheme, the colors are back to white, even if I re-run the code I posted above 🤔

**Comment by sphamba** [comment]
@bew Please check #66, revision [6686744](https://github.com/sphamba/smear-cursor.nvim/commit/668674428377c217a96350bcf5a7fc6e23747fdc), and see if it works for you!

**Comment by bew** [comment]
Awesome thanks a lot it's great now ✨ ✨ ✨ :heart:
