### ISSUE TITLE
Trail relative to buffer instead of screen when scrolling

### ISSUE THREAD

**Issue by bew** [sphamba/smear-cursor.nvim#51]
When navigating a file by search pattern, the cursor trail can get _really confusing_:
When I'm always going down in the buffer, the trail sometimes goes up when the cursor moves _up_ in screen-space, but really _down_ in buffer-space.

It's indeed consistent with what terminals can do since they can only follow terminal/screen-space positions of the cursor, but since this is implemented in neovim we know the cursor really is moving down, so the trail should follow this..

(using `trailing_stiffness = 0.05` for extra effect)

https://github.com/user-attachments/assets/e4570da0-e60b-477a-ab8c-3d14a3136c5c

In this video I'm only going _down_ in the buffer (buf line number is always increasing):
1. From line 1 to 7 to 17: (normal) Cursor and trail move down
2. From 17 to 34: (normal) Cursor and trail move down
3. From 34 to 60: (**BUG**) Cursor and trail move UP

Instead I'd expect the trail to come from the top of the buffer (out of screen) and join the new position of the cursor 🤔

It should only do that when moving in the same buffer in the same window, I think you still need to track screen-space position to properly show the trail when moving from window to window.

What do you think?

## Environment

- OS: NixOS
- Terminal: Wezterm
- Neovim version: v0.10.1
- Smear-cursor version/commit: v0.2.0

**Comment by sphamba** [comment]
I agree. There could at least be an option to choose between screen space and buffer space when scrolling inside a buffer. (Note to myself or anyone else wanting to implement this:)
- There is some code left commit [62d44095](https://github.com/sphamba/smear-cursor.nvim/tree/62d4409507e4a9696c1acd8e25904f4fb5909abe), in [screen.lua](https://github.com/sphamba/smear-cursor.nvim/blob/62d4409507e4a9696c1acd8e25904f4fb5909abe/lua/smear_cursor/screen.lua#L43) that can be used to count how many screen lines there are between two buffer lines, taking into account folds and wrapped lines
- the previous and current buffer id and line number should be saved and compared to know when to use screen position or buffer position when smearing

**Comment by sphamba** [comment]
I implemented something, available on revision [f0f1e41](https://github.com/sphamba/smear-cursor.nvim/commit/f0f1e41bbfefd6904fe399ba07328f5073bcd42c).
Please tell me if this corresponds to what you expected!

**Comment by bew** [comment]
Oh yeah it's _perfect_ ✨✨
Thanks a lot!!

---

Video for comparison with OP:

https://github.com/user-attachments/assets/5566b062-1878-408e-85b7-aa47d2dde203
