### ISSUE TITLE
add exclude filetype

### ISSUE THREAD

**Issue by melsiir** [sphamba/smear-cursor.nvim#53]
i face issue of lagging with markdown file i would like to see feature that allow me to disable the plugin in certain filetypes

**Comment by sphamba** [comment]
Indeed that could be useful. For now, you could use autocmds to detect when you enter or leave a markdown file and call `require("smear_cursor").enabled = false` or `true`

Out of curiosity, do you have specific plugins related to markdown files that would induce slowdown with smear-cursor?

**Comment by sphamba** [comment]
On which commit of smear-cursor are you? I think the behavior you observe (jumps) would arise in an older version.

**Comment by sphamba** [comment]
Just pushed a way to exclude filetypes. You can now do
```lua
opts = {
  filetypes_disabled = { "markdown" },
}
```
