### ISSUE TITLE
Black box in top-left corner where signcolumn is

### ISSUE THREAD

**Issue by YodaEmbedding** [sphamba/smear-cursor.nvim#55]
`:set signcolumn=auto:1-3`
`Ggg}}{{{}}` randomly. Eventually, a black box appears.

<img width="764" alt="Screenshot 2024-12-08 at 5 32 24 AM" src="https://github.com/user-attachments/assets/fb655bdb-d63c-4082-ab39-ed6923e07828">

## Environment

- OS: macOS
- Terminal: iTerm 2
- Neovim version: v0.10.1
- Smear-cursor version/commit: 3cacbf0

**Comment by sphamba** [comment]
Could you try smear-cursor v0.2.0 or v0.3.0 and see if it still happens? The management of floating windows has changed since then (hiding them completely when possible)
