### ISSUE TITLE
flickering neighbours

### ISSUE THREAD

**Issue by dvogt23** [sphamba/smear-cursor.nvim#6]
hey great plugin, like the neovide vibe :)

have some weird flickering letters, is it just for me?

If I go left/right the source letter going hidden, on up/down the upper neighbours of destination going hidden 🤔 
![cursor](https://github.com/user-attachments/assets/aa565a5d-96e2-4c04-bade-0877b2f5658e)

any ideas?

**Comment by sphamba** [comment]
Can be mitigated with faster smear config. Instructions are now in the README
