### ISSUE TITLE
No smear on `zt`, `zz`, or `zb` with `scroll_buffer_space = true`

### ISSUE THREAD

**Issue by sphamba** [sphamba/smear-cursor.nvim#62]
The smear does not appear on `zt`, `zz`, or `zb` movements when `scroll_buffer_space = true`. It appears correctly when `scroll_buffer_space = false`.

## Environment

- Neovim version: v0.10.2
- Smear-cursor version/commit: [f0f1e41](https://github.com/sphamba/smear-cursor.nvim/commit/f0f1e41bbfefd6904fe399ba07328f5073bcd42c)

**Comment by bew** [comment]
Nice, works well now 👍
