### ISSUE TITLE
Cursor Flickering when an error notification shows up(floating) from nvim notify

### ISSUE THREAD

**Issue by kyoryo** [sphamba/smear-cursor.nvim#64]
I got a flickering condition when nvim-notify showing me an error message. The flickering will be gone when the floating window is gone. And if I press any key (such as leader, or q) the flickering is also gone temporarily until I pressed an escape.

https://github.com/user-attachments/assets/90fd5690-9ec4-4f64-8723-66a0daf30a38

To reproduce this Try to call these command with nvim-notify installed. 
```
:lua vim.notify("This is an error message.\nSomething went wrong!", "error", { title = "custom Error", on_open = function() vim.notify("Attempting recovery.", vim.log.levels.WARN, { title = plugin, }) local timer = vim.loop.new_timer() timer:start(2000, 0, function() vim.notify({ "Fixing problem.", "Please wait..." }, "info", { title = plugin, timeout = 3000, on_close = function() vim.notify("Problem solved", nil, { title = plugin }) vim.notify("Error code 0x0395AF", 1, { title = plugin }) end, }) end) end, })
```
It seems only specific error levels give me the flickering.

## Environment

- OS: Win11 - WSL Ubuntu 20.04
- Terminal: Windows Terminal
- Neovim version: 0.10.2
- Smear-cursor version/commit: 2d1552a

**Comment by sphamba** [comment]
Does it happen with `hide_taget_hack = false`?

**Comment by kyoryo** [comment]
yep, you could also see all of my smear config options on my video.

**Comment by sphamba** [comment]
Indeed, I also get flickering. However, even with smear-cursor disabled, I get the same amount of flickering. How is it for you?

**Comment by kyoryo** [comment]
Yea me too. I didn't know it was nvim notify problem. This issue can be closed then. Thanks for replying.
