### ISSUE TITLE
Support Warp, Alacritty, or others?

### ISSUE THREAD

**Issue by A-caibird** [sphamba/smear-cursor.nvim#65]
Ask your question about configuring or using smear-cursor here.

## Environment (optional)

- OS:
- Terminal:
- Neovim version:
- Smear-cursor version/commit:

**Comment by bew** [comment]
What's your question? the plugin works for any terminal, especially if it does not have support for cursor trails

**Comment by sphamba** [comment]
> This plugin is intended for terminals/GUIs **that can only display text and do not have graphical capabilities** (unlike [Neovide](https://neovide.dev/), or the [Kitty](https://sw.kovidgoyal.net/kitty/) terminal)

However, if you find a terminal where this plugin does not work, please open a bug issue.
