### ISSUE TITLE
Setting `cursor_color` to `none` keeps reporting error when moving cursor

### ISSUE THREAD

**Issue by hezhizhen** [sphamba/smear-cursor.nvim#68]
Here's the configuration for smear-cursor: 

```lua
  opts = {
    hide_target_hack = true,
    cursor_color = "none",
  }
```

And smear-cursor keeps reporting error when I move cursor:

```text
                     Error executing vim.schedule lua callback: ...e/nvim/lazy/smear-cursor.nvim/lua/smear_cursor/color.lua:67: bad argument #1 to 'tonumber' (string expected, got nil)
stack traceback:
	[C]: in function 'tonumber'
	...e/nvim/lazy/smear-cursor.nvim/lua/smear_cursor/color.lua:67: in function 'hex_to_rgb'
	...e/nvim/lazy/smear-cursor.nvim/lua/smear_cursor/color.lua:76: in function 'interpolate_colors'
	...e/nvim/lazy/smear-cursor.nvim/lua/smear_cursor/color.lua:139: in function 'get_hl_group'
	...re/nvim/lazy/smear-cursor.nvim/lua/smear_cursor/draw.lua:277: in function 'get_right_block_properties'
	...re/nvim/lazy/smear-cursor.nvim/lua/smear_cursor/draw.lua:311: in function 'draw_horizontally_shifted_sub_block'
	...re/nvim/lazy/smear-cursor.nvim/lua/smear_cursor/draw.lua:601: in function 'draw_quad'
	...im/lazy/smear-cursor.nvim/lua/smear_cursor/animation.lua:287: in function 'change_target_position'
	.../nvim/lazy/smear-cursor.nvim/lua/smear_cursor/events.lua:8: in function ''
	vim/_editor.lua: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

## Environment

- OS: macOS 15.2
- Terminal: wezterm 20240203-110809-5046fc22
- Neovim version: v0.10.2
- Smear-cursor version/commit: 01ac0956e58ac9437a549ae091d0818500b0c4f7

**Comment by chianyungcode** [comment]
I'm experienced this bug also

**Comment by thanhtuvietnam** [comment]
{
    "sphamba/smear-cursor.nvim",
    event = "VeryLazy",
    cond = vim.g.neovide == nil,
    opts = {
      hide_target_hack = true,
      cursor_color = "#FF0000", -- Màu đỏ
    },
    specs = {
      {
        "echasnovski/mini.animate",
        optional = true,
        opts = {
          cursor = { enable = false },
        },
      },
    },
  },
you can change the setting like this and it'll be solved

**Comment by fang2hou** [comment]
for lazyvim users, after import smear-cursor from lazyvim extra, adding below to temporarily remove the option.
```
	{
		"sphamba/smear-cursor.nvim",
		opts = function(_, opts)
			opts.cursor_color = nil
			return opts
		end,
	},
```

**Comment by sphamba** [comment]
It should be fixed now, please reopen if that's not the case. Sorry for this!
