### ISSUE TITLE
Wrong start when switching between brackets

### ISSUE THREAD

**Issue by mageOfstructs** [sphamba/smear-cursor.nvim#74]
When pressing '%' on a bracket, the animation doesn't start from the cursor position (see video).

https://github.com/user-attachments/assets/10b5a339-0fe4-4b3b-9a8e-3bb8864f3d10

## Environment

- OS: Archlinux
- Terminal: kitty
- Neovim version: v0.10.3
- Smear-cursor version/commit: e6de22f

**Comment by sphamba** [comment]
Yep, I think that the reason is the same as #73.
In the meantime, v0.3.3 does not have this issue.
